language: generic
sudo: required
services:
  - docker

before_install:
  - bocker build -t xps17/docker-react -f Dockerfile.dev .

script:
  # - docker run xps17/docker-react npm run test -- --coverage
  - docker run -e CI=true xps17/docker-react npm run test